defaults: &defaults
  adapter: postgresql
  host: localhost
  username: hashpay
  password: password1

development:
  database: db_development
  <<: *defaults

test:
  database: db_test
  <<: *defaults

production:
  database: db_production
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  <<: *defaults