defaults: &defaults
  adapter: postgresql
  host: localhost
  username: hashpay
  password: password1

development:
  <<: *defaults
  database: db_development


test: &test
  <<: *defaults
  database: db_test

production:
  <<: *defaults
  database: db_production
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>


cucumber:
  <<: *defaults
  database: db_test